[package]
name = "lstm-proptest-onnx-vs-tf"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
proptest = "1.0.0"
tract-tensorflow = { path = "../../tensorflow" }
tract-onnx = { path = "../../onnx" }
