[package]
name = "tf-moz-deepspeech"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
log = "0.4.14"
tract-tensorflow = { path = "../../tensorflow" }

[dev-dependencies]
env_logger = "0.9.0"
