[package]
name = "core-proptest-pulse"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
tract-pulse = { path = "../../pulse" }
tract-hir = { path = "../../hir" }

[dev-dependencies]
log = "0.4.14"
proptest = "1.0.0"
env_logger = "0.9.0"
